# Application properties that need to be
# embedded within the web application can be included here

cas:
  service-registry:
    core:
      init-from-json: true # scan services from json
    json:
      location: file:///etc/cas/services
    schedule:
      repeat-interval: 120000
  authn:
    accept:
      enabled: false # disable default static authentication
    rest:
      uri: ${DEBUG_APP_DOMAIN}/api/debug/authenticate # refer authenticate action to DebugApplication
  logout:
    follow-service-redirects: true